[tool.poetry]
name = "workaround-for-editable-install"
version = "0.0.1"
description = ""
authors = ["none"]

[tool.poetry.dependencies]
# The Python version should match the range used in upstream:
# https://github.com/kserve/kserve/blob/v0.15.2/python/sklearnserver/pyproject.toml#L13
python = ">=3.9,<3.13"
kserve = { path = "../python/kserve", develop = false }
sklearnserver = { path = "../python/sklearnserver", develop = false }

