[tool.poetry]
name = "workaround-for-editable-install"
version = "0.0.1"
description = ""
authors = ["none"]

[tool.poetry.dependencies]
# This range should match that used upstream: https://github.com/kserve/kserve/blob/v0.11.2/python/artexplainer/pyproject.toml#L13
python = ">=3.9,<3.12"
kserve = { path = "../python/kserve", develop = false }
artserver = { path = "../python/artexplainer", develop = false }
